"""add year rating genre and director to items

Revision ID: 6769fbf3f6e2
Revises: 
Create Date: 2025-11-29 14:10:42.927066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6769fbf3f6e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('director', sa.String(length=100), nullable=True))
    op.add_column('items', sa.Column('genre', sa.String(length=100), nullable=True))
    op.add_column('items', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'rating')
    op.drop_column('items', 'genre')
    op.drop_column('items', 'director')
    op.drop_column('items', 'year')
    # ### end Alembic commands ###
